mkdir build
pushd build

if [[ "${target_platform}" == osx-* ]]; then
    export CXXFLAGS="$CXXFLAGS -D_LIBCPP_DISABLE_AVAILABILITY"
fi

cmake ${CMAKE_ARGS} \
    -DCMAKE_BUILD_TYPE=release \
    -DBUILD_TESTING=OFF \
    -DOPENSSL_ROOT_DIR=$PREFIX \
    -DOPENSSL_USE_SHARED_LIBS=ON \
    -DODBC_INCLUDE_DIRECTORIES=$PREFIX/include \
    -DCH_ODBC_RUNTIME_LINK_STATIC=OFF \
    -DCH_ODBC_PREFER_BUNDLED_FOLLY=OFF \
    -DCH_ODBC_PREFER_BUNDLED_GOOGLETEST=OFF \
    -DCH_ODBC_PREFER_BUNDLED_ICU=OFF \
    -DCH_ODBC_PREFER_BUNDLED_NANODBC=OFF \
    -DCH_ODBC_PREFER_BUNDLED_POCO=OFF \
    -DCH_ODBC_PREFER_BUNDLED_SSL=OFF \
    -DCH_ODBC_PREFER_BUNDLED_THIRD_PARTIES=OFF \
    -DCH_ODBC_THIRD_PARTY_LINK_STATIC=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DUNBUNDLED=ON \
    -GNinja ..

ninja
ninja install

popd
