mkdir build
pushd build

cmake ${CMAKE_ARGS} \
    -DCMAKE_BUILD_TYPE=release \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_LIBDIR=$PREFIX/lib \
    -DCH_ODBC_ENABLE_TESTING=OFF \
    -DOPENSSL_ROOT_DIR=$PREFIX \
    -DOPENSSL_USE_SHARED_LIBS=ON \
    -DOPENSSL_SSL_LIBRARY=$PREFIX/lib/libssl${SHLIB_EXT} \
    -DOPENSSL_CRYPTO_LIBRARY=$PREFIX/lib/libcrypto${SHLIB_EXT} \
    -DODBC_INCLUDE_DIRECTORIES=$PREFIX/include \
    -DCH_ODBC_PREFER_BUNDLED_THIRD_PARTIES=OFF \
    -DUNBUNDLED=ON \
    -GNinja ..

ninja
ninja install

popd
