mkdir build
pushd build

cmake \
    -DCMAKE_BUILD_TYPE=release \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_LIBDIR=$PREFIX/lib \
    -DOPENSSL_ROOT_DIR=$PREFIX \
    -DOPENSSL_SSL_LIBRARY=$PREFIX/lib/libssl${SHLIB_EXT} \
    -DOPENSSL_CRYPTO_LIBRARY=$PREFIX/lib/libcrypto${SHLIB_EXT} \
    -DCH_ODBC_ENABLE_TESTING=OFF \
    -DCH_ODBC_PREFER_BUNDLED_POCO=OFF \
    -DCH_ODBC_PREFER_BUNDLED_SSL=OFF \
    -DCH_ODBC_PREFER_BUNDLED_GOOGLETEST=OFF \
    -DCH_ODBC_PREFER_BUNDLED_NANODBC=OFF \
    -DCH_ODBC_PREFER_BUNDLED_FOLLY=ON \
    -GNinja ..
    # Using system for folly is not yet supported
    # -DCH_ODBC_PREFER_BUNDLED_FOLLY=OFF \
    # -DCH_ODBC_PREFER_BUNDLED_THIRD_PARTIES=OFF \

ninja
ninja install

popd
