{% set name = "clickhouse-odbc" %}
{% set version = "1.1.10.20210822" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yandex/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 440348a93e6377e21a2ea7bb1db7faadc365d9ddf361b7776279a8b56280de77
  patches:
    # https://github.com/yandex/clickhouse-odbc/pull/150
    - cac38224ae9ac657c80f56410e701b1509d03333.patch
    # This patch is already merged in master
    - 72c8e9acd1a28c501b2bcb2306b8f242b5b73fb6.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openssl
    - poco
    - libtool
    - unixodbc
  run:
    - openssl
    - poco
    - unixodbc

test:
  commands:
    - test -f $PREFIX/lib/odbc/libclickhouseodbc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/odbc/libclickhouseodbcw${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/yandex/clickhouse-odbc
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ODBC driver for ClickHouse
  doc_url: http://clickhouse.yandex/
  dev_url: https://github.com/yandex/clickhouse-odbc

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
