{% set name = "clickhouse-odbc" %}
{% set version = "1.3.2.20250227" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yandex/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 464b5c8d94e864b2fbc093aab572b5a798524c9dc5f483050b71dd14dde03bf8
  patches:
    - 0001-Add-missing-path-suffixes.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - openssl
    - poco
    - libtool
    - unixodbc
    - icu
    - folly

test:
  commands:
    - test -f $PREFIX/lib/libclickhouseodbc${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libclickhouseodbcw${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/yandex/clickhouse-odbc
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'ODBC driver for ClickHouse'
  doc_url: http://clickhouse.yandex/
  dev_url: https://github.com/yandex/clickhouse-odbc

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
