schema_version: 1

context:
  name: clickhouse-odbc
  version: "1.5.3.20260311"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/yandex/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: bb9311b48ddcd499ed2222a72a07f168f3d4909bd77ec69a78c665784b81c1c1
  patches:
    - 0001-Add-missing-path-suffixes.patch
    - 0002-libcxx-char-traits-compat.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - openssl
    - poco
    - libtool
    - unixodbc
    - icu
    - folly

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libclickhouseodbc${SHLIB_EXT}
          - test -f $PREFIX/lib/libclickhouseodbcw${SHLIB_EXT}
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: ODBC driver for ClickHouse
  homepage: https://github.com/yandex/clickhouse-odbc
  repository: https://github.com/yandex/clickhouse-odbc
  documentation: http://clickhouse.yandex/

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
